"""Add gambar to production_articles

Revision ID: 0e9eba4673e5
Revises: b1cebdb08eb1
Create Date: 2025-11-06 06:08:42.902953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e9eba4673e5'
down_revision = 'b1cebdb08eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gambar', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_articles', schema=None) as batch_op:
        batch_op.drop_column('gambar')

    # ### end Alembic commands ###
