"""tambah tabel gudang

Revision ID: 26aedb99d31a
Revises: a6e381195edd
Create Date: 2025-11-20 11:03:31.902731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26aedb99d31a'
down_revision = 'a6e381195edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal_beli', sa.DateTime(), nullable=True),
    sa.Column('nama_bahan', sa.String(length=100), nullable=False),
    sa.Column('nama_toko', sa.String(length=100), nullable=True),
    sa.Column('jumlah', sa.Float(), nullable=True),
    sa.Column('satuan', sa.String(length=20), nullable=True),
    sa.Column('harga_satuan', sa.Float(), nullable=True),
    sa.Column('total_harga', sa.Float(), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_item', sa.String(length=100), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=True),
    sa.Column('stok', sa.Float(), nullable=True),
    sa.Column('satuan', sa.String(length=20), nullable=True),
    sa.Column('lokasi_rak', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_item')
    )
    with op.batch_alter_table('production_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('satuan', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('jenis_bahan', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ukuran', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_steps', schema=None) as batch_op:
        batch_op.drop_column('ukuran')
        batch_op.drop_column('jenis_bahan')
        batch_op.drop_column('satuan')

    op.drop_table('warehouse_items')
    op.drop_table('material_purchases')
    # ### end Alembic commands ###
