"""create production_records table

Revision ID: 51e0eb95279a
Revises: 
Create Date: 2025-11-05 13:28:13.555770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e0eb95279a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('vendor_bahan', sa.String(length=100), nullable=True),
    sa.Column('jenis_bahan', sa.String(length=50), nullable=True),
    sa.Column('tahap', sa.String(length=50), nullable=True),
    sa.Column('kategori_ukuran', sa.String(length=50), nullable=True),
    sa.Column('ukuran', sa.String(length=20), nullable=True),
    sa.Column('metode_sablon', sa.String(length=50), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_records')
    # ### end Alembic commands ###
