"""tambah pengiriman

Revision ID: 9f8bd16c0875
Revises: 26aedb99d31a
Create Date: 2025-11-20 11:28:27.124602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8bd16c0875'
down_revision = '26aedb99d31a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_surat', sa.String(length=50), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('nama_penerima', sa.String(length=150), nullable=False),
    sa.Column('alamat_tujuan', sa.Text(), nullable=False),
    sa.Column('no_telp', sa.String(length=20), nullable=True),
    sa.Column('nama_kurir', sa.String(length=100), nullable=True),
    sa.Column('nopol_kendaraan', sa.String(length=20), nullable=True),
    sa.Column('jenis_kendaraan', sa.String(length=50), nullable=True),
    sa.Column('list_barang', sa.Text(), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_surat')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_orders')
    # ### end Alembic commands ###
