"""tambah kolom harga_cutting dan harga_jahit

Revision ID: a6e381195edd
Revises: 0e9eba4673e5
Create Date: 2025-11-10 10:21:18.852395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e381195edd'
down_revision = '0e9eba4673e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('harga_cutting', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('harga_jahit', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_steps', schema=None) as batch_op:
        batch_op.drop_column('harga_jahit')
        batch_op.drop_column('harga_cutting')

    # ### end Alembic commands ###
