"""add detailed fields to production steps

Revision ID: b1cebdb08eb1
Revises: fde41019136e
Create Date: 2025-11-05 19:28:52.618203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1cebdb08eb1'
down_revision = 'fde41019136e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_toko', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('jumlah', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('warna_bahan', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('harga_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ukuran_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ekspedisi', sa.String(length=100), nullable=True))
        batch_op.drop_column('ukuran')
        batch_op.drop_column('vendor_bahan')
        batch_op.drop_column('jenis_bahan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jenis_bahan', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('vendor_bahan', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('ukuran', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('ekspedisi')
        batch_op.drop_column('ukuran_data')
        batch_op.drop_column('harga_total')
        batch_op.drop_column('warna_bahan')
        batch_op.drop_column('jumlah')
        batch_op.drop_column('nama_toko')

    # ### end Alembic commands ###
