"""tambah lokasi gudang

Revision ID: ce22d0b08da3
Revises: 9f8bd16c0875
Create Date: 2025-11-20 12:45:58.508791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce22d0b08da3'
down_revision = '9f8bd16c0875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lokasi_gudang', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_items', schema=None) as batch_op:
        batch_op.drop_column('lokasi_gudang')

    # ### end Alembic commands ###
