"""add production article and step

Revision ID: fde41019136e
Revises: 51e0eb95279a
Create Date: 2025-11-05 13:36:47.445206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde41019136e'
down_revision = '51e0eb95279a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_artikel', sa.String(length=150), nullable=False),
    sa.Column('tanggal_dibuat', sa.DateTime(), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_artikel')
    )
    op.create_table('production_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('tahap', sa.String(length=50), nullable=True),
    sa.Column('kategori', sa.String(length=50), nullable=True),
    sa.Column('vendor_bahan', sa.String(length=100), nullable=True),
    sa.Column('jenis_bahan', sa.String(length=50), nullable=True),
    sa.Column('metode_sablon', sa.String(length=50), nullable=True),
    sa.Column('ukuran', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tanggal_update', sa.DateTime(), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['production_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_steps')
    op.drop_table('production_articles')
    # ### end Alembic commands ###
